### ISSUE TITLE
Zone does not automatically create .data directory and .data/db.json file

### ISSUE THREAD

**Issue by yungslime** [Ragzouken/zone#65]
As it says in the title, I set up a zone server and it wouldn't run until I manually created the .data directory and an empty db.json file inside it. 

This was tested on Ubuntu 16.04 with node 10.22.0

![dragon-quest-wireless-controller-for-playstation-4-518117 1](https://user-images.githubusercontent.com/25403790/89412061-b72b0380-d726-11ea-8ef6-e3aec522b1b6.jpg)

**Comment by Ragzouken** [comment]
i've made it try to create the data folder--pretty sure it can handle the `db.json` not existing (seems to work locally)
